const commonData = {
    savedCommandsList: {
        custom: "Custom command",
        deviceIdentification: "Device Identification",
        positionSingle: "Single Reporting",
        positionPeriodic: "Periodic Reporting",
        positionStop: "Stop Reporting",
        engineStop: "Engine Stop",
        engineResume: "Engine Resume",
        alarmArm: "Arm Alarm",
        alarmDisarm: "Disarm Alarm",
        setTimezone: "Set Timezone",
        requestPhoto: "Request Photo",
        powerOff: "Power Off Device",
        rebootDevice: "Reboot Device",
        sendSms: "Send SMS",
        sendUssd: "Send USSD",
        sosNumber: "Set SOS Number",
        silenceTime: "Set Silence Time",
        setPhonebook: "Set Phonebook",
        message: "Message",
        voiceMessage: "Voice Message",
        outputControl: "Output Control",
        voiceMonitoring: "Voice Monitoring",
        setAgps: "Set AGPS",
        setIndicator: "Set Indicator",
        configuration: "Configuration",
        getVersion: "Get Version",
        firmwareUpdate: "Update Firmware",
        setConnection: "Set Connection",
        setOdometer: "Set Odometer",
        getModemStatus: "Get Modem Status",
        getDeviceStatus: "Get Device Status",
        modePowerSaving: "Modify Power Saving",
        modeDeepSleep: "Modify Deep Sleep",
        movementAlarm: "Movement Alarm",
        alarmBattery: "Alarm Battery",
        alarmSos: "Alarm Sos",
        alarmRemove : "Alarm Remove",
        alarmClock: "Alarm Clock",
        alarmSpeed: "Alarm Speed",
        alarmFall: "Alarm Fall",
        alarmVibration: "Alarm Vibration"
    },
    maintenanceType: {
        index: "Index",
        hdop: "HDOP",
        vdop: "VDOP",
        pdop: "PDOP",
        sat: "Satellites",
        satVisible: "Visible Satellites",
        rssi: "RSSI",
        gps: "GPS",
        odometer: "Odometer",
        serviceOdometer: "Service Odometer",
        tripOdometer: "Trip Odometer",
        hours: "Hours",
        steps: "Steps",
        power: "Power",
        battery: "Battery",
        batteryLevel: "Battery Level",
        fuel: "Fuel",
        fuelConsumption: "Fuel Consumption",
        distance: "Distance",
        totalDistance: "Total Distance",
        rpm: "RPM",
        throttle: "Throttle",
        armed: "Armed",
        acceleration: "Acceleration",
        deviceTemp: "Device Temperature",
        obdSpeed: "OBD Speed",
        obdOdometer: "OBD Odometer"
    }
}


export default commonData;